### PR TITLE
Virtualize both FalloutNV / _Epic for plugins.txt

### PR DESCRIPTION
**Pull request by Silarn**
- Apparently BGS shipped with the launcher using one and the game using the other. (The game uses the original directory.)

### CODE REVIEW

**Comment by Silarn** [comment]
This may be patched by the community, but apparently this is necessary for the dumb bug BGS introduced.

Virtualizing both locations allows it all to work 'correctly'. I'm honestly surprised this wasn't noticed before.

**Comment by Silarn** [comment]
I never made it ignore the hidden directories. I'll have to make that change.

**Review by Holt59 — APPROVED** [review]
Maybe do a squash merge for this one.

**Comment by WilliamImm** [comment]
The changes work on my end, including for the GOG version. Variant is correctly listed.

**Comment by Silarn** [comment]
Squash merged to master

**Pull request closed without merging**
